### ISSUE TITLE
Wrong definition for adjacency list 

### ISSUE THREAD

**Issue by INF800** [deepmind/educational#3]
In the notebook [educational/summer_schools/intro_to_graph_nets_tutorial_with_jraph.ipynb](https://github.com/deepmind/educational/blob/master/colabs/summer_schools/intro_to_graph_nets_tutorial_with_jraph.ipynb) adjacency list is defined as ordered pairs.

> As an adjacency list: a list of ordered pairs (u, v).

It should be unordered right?

**Comment by lisa-1010** [comment]
Thank you for finding this error! We used the wrong term there, it should have been "list of edges" instead of "adjacency list". We will submit a fix to the colab shortly, and clarify the definition of adjacency list as well. Thanks!

**Comment by lisa-1010** [comment]
Fixed the definitions, thanks!
