### ISSUE TITLE
Fundamental Graph Concepts section missing a edge pair in the example?

### ISSUE THREAD

**Issue by pdubz-sudo** [deepmind/educational#4]
Thanks for sharing the graph knowledge and colab! It was super cool!

In the section `Fundamental Graph Concepts`, I was looking at the example and it says that the adjacency list  is a list of ordered pairs (u,v). In the example graph, there is a bi-directional edge for nodes 0 and 3. However, the representation of edges in the example says it's: [(0, 1), (1, 2), (2, 0), (3, 0)].

Shouldn't (0,3) also be in the adjacency list in that case?

![Screenshot 2022-02-13 at 17-25-34 Google Colaboratory](https://user-images.githubusercontent.com/34268692/153762647-a32f5343-cb4a-4f1c-b171-5d3ffd572ae5.png)

![Screenshot 2022-02-13 at 17-26-16 Google Colaboratory](https://user-images.githubusercontent.com/34268692/153762703-7a2fbb9f-fb73-4c5c-a9c7-bd66557758a3.png)

**Comment by lisa-1010** [comment]
Thank you for finding this error and for letting us know! Will submit a fix shortly. Glad to hear you enjoyed the colab.

**Comment by lisa-1010** [comment]
Fixed, thanks again!

**Comment by lisa-1010** [comment]
Fixed in https://github.com/deepmind/educational/commit/f31d6bd4addf070beec90a8c4d4949feb9be0660
